name: Deploy to server
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello, my world!"
    steps:
      - name: Hello World
        run: echo $MY_ENV_VAR
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.step_1.outputs.my_variable }}
    needs: first_job
    steps:
      - name: Hello Again
        run: echo "Hello again, ${{ github.ref == 'refs/heads/main' }}!"
      - name: Variables
        id: step_1
        run: echo "my_variable=Hola" >> $GITHUB_OUTPUT
      - name: Show Variables
        run: echo "result is ${{ steps.step_1.outputs.my_variable }}"
  third_job:
    runs-on: ubuntu-latest
    needs: second_job
    env:
      my_input: ${{ needs.second_job.outputs.my_output }}
    steps:
      - name: dir listing before
        run: ls -la
      - name: Action
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: dir listing after
        run: ls -la
      - name: Show Input
        run: echo "my_input is ${{ env.my_input }}"
  fouth_job:
    runs-on: ubuntu-latest
    needs: third_job
    steps:
      - name: Generate file
        run: |
          echo "Test file content" >> test_file.log
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: test_file
          path: test_file.log
  fifth_job:
    runs-on: ubuntu-latest
    needs: fouth_job
    steps:
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: test_file
      - name: Show file content
        run: cat test_file.log