name: Deploy to server
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello, my world!"
    steps:
      - name: Hello World
        run: echo "$MY_ENV_VAR"
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Hello Again
        run: echo "Hello again, ${{ github.ref == 'refs/heads/main' }}!"  
    