name: my 1rs workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A new commit has been pushed to the main branch!"
      - run: echo "Building the project..."
      - run: echo "Running tests..."
      - run: echo "Deployment successful!"